
**Name** : Airyll H. Sanchez

**Section**: DS4A

**Date**: September 3, 2025

## Laboratory Task # 5

![laboratory5](images/Laboratory5.1.png)

1. Perform Standard Imports

In [1]:
import torch
import numpy as np
import sys
import random

![image.png](images/Laboratory5.2.png)

In [2]:
def set_seed(seeed: int) -> None:
    torch.manual_sed(seed)
    random.seed(seeed)
    np.random.seed(seeed)

![laboratory](images/Laboratory5.3.png)

In [3]:
def set_seed(seed):
    np.random.seed(seed)

set_seed(42)
arr = np.random.randint(0, 5, 6)
print (arr)

[3 4 2 4 4 1]


![image](images/Laboratory5.4.png)

In [4]:
x = torch.from_numpy(arr)
print("PyTorch tensor:", x)

PyTorch tensor: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


![image](images/Laboratory5.5.png)

In [5]:
dt = x.type(torch.int64)
print(dt)
print(dt.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


![image.png](images/Laboratory5.6.png)

In [6]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [7]:
x = x.reshape(3,2)
print("Reshaped tensor:\n", x)
print("New shape:", x.shape)

Reshaped tensor:
 tensor([[0, 1],
        [2, 3],
        [4, 5]])
New shape: torch.Size([3, 2])


![image.png](images/Laboratory5.7.png)

In [8]:
x[:,1]

tensor([1, 3, 5])

![image.png](images/Laboratory5.8.png)

In [9]:
squared_x = x ** 2
print("Squared tensor:\n", squared_x)

Squared tensor:
 tensor([[ 0,  1],
        [ 4,  9],
        [16, 25]])


 ![image.png](images/Laboratory5.9.png)

In [10]:
set_seed(42)
y = torch.randint(low=0,high=5,size=(2,3),dtype= torch.int64)
y

tensor([[4, 3, 0],
        [0, 2, 1]])

![image.png](images/Laboratory5.10.png)

In [11]:
print(torch.mm(x,y))

tensor([[ 0,  2,  1],
        [ 8, 12,  3],
        [16, 22,  5]])
